comment: false

ignore:
  - R/utils_logging.R
  - R/MSstats_exports.R
  - R/utils_check.R

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
