name: Dry runs for PRs
on: 
  pull_request:
<<<<<<< HEAD
    branches: [master]
=======
    branches: [devel]
>>>>>>> aca951e22891075019e3d8ebf64b3f5833eef6a1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: release
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1

